### PR TITLE
added ADR for the JUnit test engine

### PR DESCRIPTION
**Pull request by slu-it**
This is a draft...

### CODE REVIEW

**Comment by Drakojin** [comment]
I don't think a complete abandonment of the UI functionalities would be wise.

**Comment by bitterblue** [comment]
It's not our top goal, but I don't think we discussed yet how this would affect support for fixture languages other than Java.

**Comment by Drakojin** [comment]
True we did'nt.

If we keep those we have to modify them. Like decoupling downloading from execution. Foremost we should decide what the purpose of the plugins is. 

Right now every other language which is not JVM will prove a challenge.

**Comment by slu-it** [comment]
@bitterblue should we merge now and you add your additions in a separate PR, or do you want to checkout my branch, add your stuff and create a new MR? I'm good either way.

**Comment by bitterblue** [comment]
@slu-it merging now is fine. I tried to yesterday, but the branch is not up-to-date. Could you?

**Pull request merged**
